app = "hookkeeper-api"
primary_region = "ord"

[build]

[deploy]
  release_command = ""

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_exit = false

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  size = "sv1"
